### PR TITLE
PNDA-3039: Organise Applications List on console

### PR DESCRIPTION
**Pull request by Deepa-Martin-ML**
# Problem Statement:
PNDA 3039: Console Application text entry is small and Applications are not organised properly.

# Analysis:
- Application List in console home page is not scrollable.
- Does not allow search/filter applications by name.

# Change:
- Scrollbar to allow users to scroll up/down applications listed in a page.
- Add search box to allow search or filter applications by name.

### CODE REVIEW

**Comment by trsmith2** [comment]
Could you please resolve the conflicts in this?

**Comment by shubhi0310** [comment]
@trsmith2 : Resolved the merge conflicts.

**Comment by trsmith2** [comment]
This looks pretty good, thanks for the PR. 

One improvement I'd suggest is that given you're now able to deal with many applications in a small space, you should start by making that space adequate given the real estate on the screen. As you can see from this clip, it looks a little strange to constrain a box to 5 items when there are more than 5, there's easily enough space to show more, and we have the items per page set higher than 5.

image

The other aspect I'd tweak to find a way to stop the left/right controls bouncing around depending on how many items exist. You could experiment with a design placing them at the top of the control rather the bottom, or, as above, maybe go for a fixed height control proportional to the screen.

**Comment by trsmith2** [comment]
Thanks for the update, I think it's cleaner without the buttons so this is an improvement. However simply making the box larger unconditionally is just another white space not being used, which was really the original point. So, how about we make the box min(items, m) where m is set to something sensible based on the browser window height (aligning with the bottom of the HDFS box to the left would probably make sense). Together with the search box, and the scroll bar, this should be enough  for anyone to be able to navigate around apps.

**Comment by shubhi0310** [comment]
@trsmith2 I have updated the code. Removed the hardcoded value for height. Now it will adjust based on screen size.

**Comment by trsmith2** [comment]
This doesn't merge, could you please address the conflicts

**Comment by shubhi0310** [comment]
@trsmith2 Hi Trevor, I resolved the conflicts.

**Comment by trsmith2** [comment]
This is better. Can you use the value of the y coordinate for the bottom of the HDFS box to the left as 'm' in 'min(items, m)'. I think that coordinate is probably based on the screen height rather than the current resized browser window height, which means that once decided it won't change every time you change the size of the browser. 

image

**Comment by shubhi0310** [comment]
Hi trevor,
I made the changes as you suggested. Now deployment-manager will always have maximum height till HDFS.

**Pull request merged**
