### PR TITLE
Pnda 2834 Added a popup to display status of each sub component of each application

### PR DESCRIPTION
**Pull request by Deepa-Martin-ML**
**Problem Statement:**
PNDA 2834: There was only aggregate status of an application displayed to user. User cannot see the status of individual jobs of an application.

**Analysis:**
If an application is failed then its important for user to see which job or sub component failed. For that, user must see the status and ID of all the sub components of an application.

**Change**:
We have added a new link with application name on applications page called as "More Info". When user will click on this link , a pop up will open. There user can see all the sub component of that application with name, type, ID and status.

### CODE REVIEW

**Comment by jeclarke** [comment]
Hi @deepamartin, I've given this a go and I think it is a good start. Could you make a couple of minor usability improvements:

 - put the 'more info' link next to the status in status column, or make the status itself the link. It isn't super obvious where to click to see the enhanced summary right now.
 - link from items in summary pop up to relevant yarn resource manager job page. This would be really helpful.

Thanks,
James

**Comment by jeclarke** [comment]
Hi @deepamartin I've spotted something more fundamental that will need fixing too. You have to click off the highlighted application row and then back on it again for the more info link to show anything different, this is against the design of the console which generally uses websockets to update without having to reload the page at all. This will confuse users. At a minimum the data should be fetched fresh when 'more info' is clicked, and ideally the status summary page should be updated by websockets events without closing and reopening it.

Can you also look into doing that? If the websockets is too much work to add-on, then we can make a note of that as a future enhancement, but when more info is clicked, it needs to fetch new data.

Thanks,
James

**Comment by jeclarke** [comment]
Hi again @deepamartin, we had a discussion in the team and decided to merge this and track the improvements above as defects. Let us know if you work on any of them, so we don't duplicate effort.

Thanks!
James

**Comment by Deepa-Martin-ML** [comment]
Hi James,
We had just started discussion on how to implement the changes.

Regards,
Deepa M

**Comment by Deepa-Martin-ML** [comment]
Hi @jeclarke , Thanks for your comments. There are few things in which we need clarifications:

1. Shall we open the issues for changing the location of "More Info" link and making job Id as URL?
2. We have not implemented auto-refresh for getting the status summary because we are afraid if there are multiple sessions are active at the same moment then backend may get overloaded.

**Comment by trsmith2** [comment]
I agree that continually refreshing is going to cause unnecessary load. Can we track state transitions? If we can't (directly), can we monitor <something> on a more lightweight basis (e.g. YARN UI?) and use that as a trigger to do a deeper check only when something really has changed?

**Comment by Deepa-Martin-ML** [comment]
@trsmith2: so are we talking about web sockets for this?

**Pull request merged**
